
server:
  port: 8083
spring:
  application:
    name: CookingApp
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/cooking_app
    username: root
    password: abcd1234
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:orcl
#    username: cooking
#    password: abcd1234
  jpa:
    properties:
      hibernate:

    hibernate:
      ddl-auto: none
    show-sql: true

project:
  foodimage: foodimage/


base:
  url: "http://localhost:8083"



openapi:
  service:
    api-docs: api-service
    server: http://localhost:8083
    title: API Service
    version: 1.0.0

    # mat file application.properties r
