
server:
  port: 8083
  servlet:
    context-path: /cookingapp
spring:
  application:
    name: CookingApp
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/cooking_app
    username: root
    password: abcd1234
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:orcl
#    username: cooking
#    password: abcd1234
  jpa:
    properties:
      hibernate:

    hibernate:
      ddl-auto: none
    show-sql: true

project:
  foodimage: foodimage/


base:
  url: "http://localhost:8083"

jwt:
  signerKey: "hlPp9x4GIOQVHBewHlAtg2PJtw98OFrY0IOmYv4EC9zpmU5sUcqBtP2rW+gsJ2vX"
  valid-duration: 3600 #in second #het han sau
  refreshable-duration: 120 #second #token moi co thoi han

openapi:
  service:
    api-docs: api-service
    server: http://localhost:8083
    title: API Service
    version: 1.0.0